edition = "2021"
newline_style = "Unix"
reorder_modules = true
use_small_heuristics = "Default"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
reorder_impl_items = true
comment_width = 100
wrap_comments = true
normalize_comments = true
