---
name: 'Release'

"on": workflow_dispatch

permissions:
  contents: write
  id-token: write
  packages: write


concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  release:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: HatsuneMiku3939/direnv-action@v1
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - run: bazel run -c opt --embed_label="$(git describe --tags HEAD)" //blade:blade_push